language: node_js
node_js:
- '7'
branches:
  only:
  - master
  - /^greenkeeper/.*$/
before_script:
- npm install -g @angular/cli
script:
- ng build --prod
env:
  global:
  - secure: aJQrUzkliz3jF6gMzv00y/wo/wLEApjH0hpBh6EJUTWxajQSUVY0UyS6mmQz92cY+bByUcy1keASNM5y4L20yFta2Q6+jBc2Kx34cSJgBXDEBQ8kkY0VMicr/75Afuvh36rv8bMkCNgMm6JvH7tcEkxRo180DB6i6+tY+UzPXVtCircZct12Xb9+kvbZaS4X1vHSOkZrPwuNZYv1VbyGSPvPKgYHeugU+scf3VFrwn0FYxjlSsAbsuQqe5e+L5HQpHxVhwtTrcD8LdGlqzQFe/TZvzAeO7XGaba9JFxXk9m+r29QjWK631Ts0/BxmxRwphnneFT1aD0Dv3m2kroWmAKVualPjf92RQf3S6XAaxZpl6ECmyadcvNS0FCXB6yX0Kv13fzAAC3qtmlTKjqYjxqqQN8sJxx/Yv0k9U9PEBhBNMhYrfzlJ/8gKvUq9K50Pq4rpbd5qw5+QrDQwclYpKAumgSAASN6W4RGCm3Ug6Gv65sH2+KcbtaSXzouAWUj3jkEg/jOqDQf2ngn3MK7zypPGeD1vebnEp6YlH5CpiNBz9G0bkua4MlOto5llkIKiHSEt0APQm17U9twvioFx9qJwWR74PMGvsdjxcI24eux/of6dFmkoc302NilFRqyq0VgLYrry9F6lhfnjfH/0rDBNX6nLr+S/ckCm7PoRFo=
  - secure: qLhzvZ/uh3AZOkzDFoPiSSydIicQd0PRidSq+AM0QhjpU10eHlQ/aq5lriEEcdKjM6FhtsSZkAUdgFdzDpMj7REUa6J+gSu+bTMSK99UG7ZOQ7o+Bba3s/YLHuQo/fSC/MzZ/mRqJ1rivzHaOkSRMSPIUC9nlyhHZnnCRMcmCyCdWh8D5h5Psp3LQfj+aqnJeuQTRKkJ3eOFgGbYiF+mMRf6diJJWnVmF5z8G/rLYpGNwxVvDstIgIjNjKIDNpbG/t9FRACuorkJHWCOUh5v9tf2mnkrJTuOXMjuowbBU/u8dAX7LyLTn/1Oqv7uzz0TjnZHaUQ3BWT5NNVu9DRjKQRSbwYN4MjJVELrDshRGD/smGVsjz0dqsEE4kpzLSB8L3K18/49gvnSwrSBbhPGfj9v/jbnKCdLmn7/ZzKvxo70eG0ZjT8j4NctrbIwTvU0hfB7y9VBJWijxCFYHiSn/JBaCoSyUC/vzgrjruPBNQnEFl6crI2ekEnkxxUuL9eAP5nZSvHs2EG6/jVAckbAb4C3rh3KDK1wIBiU2cdIkAvblaENfNwT2Rwm4hufWRkOwYUwOl05qytgWZUjb6fX3O/0/2/Iucn41wei1WjEime8ehI/fP9Zs1rE+AxaNk/hRups/IuNvYnX3KuzFGTyIAxHkcJdcG1c7zTSjP2RZAo=
  - secure: k/9OgHqafxt/gnL+UUL8yXhkQFtWvGOqo2jozMkwUt/5TCzhFFMeaXq+19yU0qQr/PE7M6JFupI2b8inGrsNezcrtVuNronsDYpxK6rIphqun6bCR756mNLlM2k2uL5udu60fjvYJz3Ry6VkeupRNsK6pJokgBksqRPXZHHXTzisaxxTkalKnn6i6lzlpWqxRd1dsNYrIdSxl1vksws2Kj8yw6WCWDycOy1EopggnX/1VIv/w2NU/M3ILZ3u0onFGFlMsPJekkoQehloo2aWgq6N0QPZVvqeLy+vpd5kq8pd3wj0x/GrcbAt1FVdgds/dYS/MSP176TE82xHrTq1qrvHyo/KqfwZojcjhz85OtIwuzxY9V1EpPQkXFN/WLWCzXYrB9KQS+y99DtpgI8fAHA7cQ5DqyLr1JELVFlRL7qz3+HiL3g74Kuoshxa8GZX+9pe2DYGXUfXj7SD7mkh272ReJYc2qt1TVwYHRHXrsjsIehGdElxzc5TxjEjuTSmSDDlyE5W0ou/oHABNc77Z6MM+AHuvVYLYQTVyG+9T+592AABt4SxY0GQphdhM3GMD5eF/LR4aIHvPIipzusnwEtMsFrxI9iRwz/w2ScT9ZYo0C7saiFBDvUfSme7vbqFSux032J9uBJxxGbuC97OvW3EjEaLygfyYxmDTRtT6GM=
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
